### ISSUE TITLE
Breaking changes in HASS 2023.9 preventing the integration to load

### ISSUE THREAD

**Issue by steynovich** [leeyuentuen/alfen_wallbox#62] opened 2023-09-06 13:36 UTC
When running alfen_wallbox with Home Assistant 2023.9 RC the integration fails to load:

```
2023-09-06 15:05:48.331 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration alfen_wallbox: Unable to import component: Exception importing custom_components.alfen_wallbox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/alfen_wallbox/__init__.py", line 21, in <module>
    from .alfen import AlfenDevice
  File "/config/custom_components/alfen_wallbox/alfen.py", line 48, in <module>
    hass = core.HomeAssistant()
           ^^^^^^^^^^^^^^^^^^^^
TypeError: HomeAssistant.__new__() missing 1 required positional argument: 'config_dir'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 826, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.alfen_wallbox
```

Most likely this will be the case for the final version. See https://developers.home-assistant.io/blog/2023/08/29/homeassistant-changed-signature/

**Comment by leeyuentuen** [comment] 2023-09-06 19:07
@steynovich  can you take a look if this beta version fix this problem?
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.6.14

**Comment by steynovich** [comment] 2023-09-06 19:19
@leeyuentuen did a small smoke test. It seems to work. Integration is loading without errors and refreshing data etc. Thanks

**Comment by leeyuentuen** [comment] 2023-09-07 06:27
@steynovich can you take a look if the problem is still fixed In this beta version?
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.6.16

**Comment by steynovich** [comment] 2023-09-07 06:48
@leeyuentuen yes, 2.6.16 works for me

**Comment by leeyuentuen** [comment] 2023-09-07 06:59
in meantime one more extra beta, but should be not changed here for you.
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.6.17

**Comment by steynovich** [comment] 2023-09-07 07:44
@leeyuentuen 2.6.17 also works for me :-)

**Closed** 2023-09-07 11:23 UTC
Labels: bug, Ready for release, dev tested, in beta (testing)
